### PR TITLE
Change Fainil source to Dragon 244

### PR DESCRIPTION
**Pull request by gene1wood**
This is in Dragon 244 page 26
This relates to #95

### CODE REVIEW

**Comment by decheine** [comment]
Thank you for the contributions! When making changes to monster source files, the compendium will need to be rebuilt. You'll need Docker but that's it.

First, run the combined command to build and harvest the monsters:

```
docker build -t monster-harvester -f harvester/Dockerfile .; docker create --name harvester-container monster-harvester; Foreach-Object { docker cp "harvester-container:/usr/local/harvester/build/bin/json_files" output }
```

Then run the helper script that copies the generated files to the repository:

```
node scripts/copy_monster_data.js
```

Then test it to see if the changes showed up right. If you have any questions let me know!

**Comment by gene1wood** [comment]
Great! I wasn't clear reading the README if a PR should contain just the source change or also the rendered change. I'll update this PR with that.

You may want to add that to the README, maybe a small section about how to contribute (with those types of commands you mention above)

**Comment by decheine** [comment]
It's usually best to just do the whole book at once, so you only have to build/run the harvester once.

**Comment by decheine** [comment]
Pushed 1c0f66b320f0282e0e5b16b19fc30f531003d187, the monsters in this book are complete. Thanks for this!

**Comment by gene1wood** [comment]
Thank you! Sorry I got swamped and wasn't able to render the content and update the PR

**Pull request closed without merging**
